# neo-minimal 主题配置
menu:
  Home: /
  Archives: /archives/
  About: /about/

github: https://github.com/neocwei

hero_title: Neo's blog
hero_subtitle: notes on code, bugs and little things in life

footer_text: © 2025 Neo
